import os
import sys
import logging
from pathlib import Path
from datetime import datetime, timedelta
from typing import Dict, List
from dotenv import load_dotenv

# Add project root to path
sys.path.append(str(Path(__file__).parent.parent.parent))

from src.utils.paths import find_vault_root, get_done_path
from src.utils.odoo_client import OdooClient
from src.utils.state_manager import StateManager

load_dotenv()

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger("BriefingAgent")

class BriefingAgent:
    def __init__(self):
        self.vault_root = find_vault_root()
        self.odoo = OdooClient()
        self.state_manager = StateManager(self.vault_root)
        self.briefings_path = self.vault_root / "Briefings" / "Weekly"
        self.briefings_path.mkdir(parents=True, exist_ok=True)

    def get_productivity_stats(self, days: int = 7) -> Dict:
        """Analyzes the Done folder for the last X days."""
        done_path = get_done_path(self.vault_root)
        cutoff = datetime.now() - timedelta(days=days)
        
        tasks_completed = 0
        bottlenecks = []
        
        if not done_path.exists():
            return {"count": 0, "bottlenecks": []}

        for task_file in done_path.iterdir():
            if task_file.is_file() and task_file.suffix == ".md":
                mtime = datetime.fromtimestamp(task_file.stat().st_mtime)
                if mtime > cutoff:
                    tasks_completed += 1
                    
                    # Analyze for bottlenecks (simulated using state manager if available)
                    state = self.state_manager.get_task_state(task_file.name)
                    if state and state.get("iteration_count", 0) > 3:
                        bottlenecks.append({
                            "name": task_file.name,
                            "iterations": state["iteration_count"]
                        })
        
        return {
            "count": tasks_completed,
            "bottlenecks": bottlenecks
        }

    def generate_briefing(self):
        """Generates the Monday Morning CEO Briefing."""
        logger.info("Generating CEO Briefing...")
        
        # 1. Get Financial Data
        start_week = (datetime.now() - timedelta(days=7)).strftime('%Y-%m-%d')
        end_week = datetime.now().strftime('%Y-%m-%d')
        revenue = self.odoo.get_revenue(start_week, end_week)
        
        # 2. Get Productivity Data
        stats = self.get_productivity_stats(7)
        
        # 3. Format Report
        date_str = datetime.now().strftime('%Y-%m-%d')
        report_name = f"{date_str}_Monday_Morning_CEO_Briefing.md"
        report_path = self.briefings_path / report_name
        
        content = f"""---
generated_at: {datetime.now().isoformat()}
period: {start_week} to {end_week}
type: ceo_briefing
---
# Monday Morning CEO Briefing

## Executive Summary
The AI Employee has completed **{stats['count']} tasks** this week. 
Total revenue logged in Odoo for this period is **${revenue:,.2f}**.

## 💰 Financial Performance
- **Weekly Revenue:** ${revenue:,.2f}
- **Odoo Status:** {"Connected" if self.odoo.odoo else "Offline (Using cached/zero data)"}

## 🚀 Productivity & Operations
- **Tasks Completed:** {stats['count']}
- **Average Throughput:** {stats['count']/7:.1f} tasks/day

### ⚠️ Bottlenecks Identified
"""
        if not stats['bottlenecks']:
            content += "- No significant bottlenecks detected. Operations are smooth.\n"
        else:
            for b in stats['bottlenecks']:
                content += f"- **{b['name']}**: Required {b['iterations']} iterations to complete.\n"

        content += """
## 💡 Proactive Suggestions
1. **Revenue Growth:** Weekly revenue is at ${:,.2f}. Consider increasing social media outreach.
2. **Efficiency:** {suggestion}
3. **Subscriptions:** Run `audit_subscriptions` tool to identify potential cost savings.

---
*Generated by Digital FTE BriefingAgent v2.0 (Gold Tier)*
""".format(revenue, suggestion="Review bottlenecks above to optimize reasoning loops." if stats['bottlenecks'] else "System is performing within optimal parameters.")

        report_path.write_text(content, encoding='utf-8')
        logger.info(f"Briefing generated at: {report_path}")
        return report_path

if __name__ == "__main__":
    agent = BriefingAgent()
    agent.generate_briefing()
